name: beam-animations
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.22.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - pycairo>=1.21.0
  - ffmpeg>=5.0
  - pytest>=7.0.0
  - black>=22.0.0
  - conda-forge::manim=0.17.3